---
- name: set local repo path name and git url with token
  set_fact:
    git_repo_path: "{{ git_url | regex_search('/(.+).git') | regex_replace('.git', '') }}"
    git_url_with_token: "{{ git_url | regex_replace('github.com', git_token@'github.com') }}"

- name: git clone "{{ git_url }}"
  shell: git clone "{{ git_url_with_token }}"
  args:
    chdir: "{{ base_working_dir }}{{ git_repo_path }}"
  ignore_errors: true
