---
- name: set git url with token
  set_fact:
    git_url_with_token: "{{ git_url | regex_replace('github.com', git_token + '@github.com') }}"

- name: git clone "{{ git_url }}"
  shell: git clone "{{ git_url_with_token }}"
  no_log: true
  args:
    chdir: "{{ base_working_dir }}"
  ignore_errors: true
