---
- name: set local repo path name
  set_fact:
    git_repo_path: "{{ git_url | regex_search('/(.+).git') | regex_replace('.git', '') }}"
    git_url_with_token: "{{ git_url | regex_replace('github.com', git_token + '@github.com') }}"

- name: git pull
  git:
   repo: "{{ git_url }}"
   dest: "{{ base_working_dir }}/{{ git_repo_path }}"
