---
- name: set "pre-trim" local repo path name
  set_fact:
    git_repo_path_pretrim: >
      {{ git_repo_url | regex_search('(?!.*\/).+') | regex_replace('.git', '') }}
    git_url_with_token: "{{ git_url | regex_replace('github.com', git_token + '@github.com') }}"

- name: set local repo path name
  set_fact:
    git_repo_path: "{{ git_repo_path_pretrim | trim }}"

- name: git add all new files
  shell: git add -A
  args:
    chdir: "{{ base_working_dir }}/{{ git_repo_path }}"

- name: git status
  shell: git status
  args:
    chdir: "{{ base_working_dir }}/{{ git_repo_path }}"
  register: git_precommit_status

- debug:
    msg: "{{ git_precommit_status }}"

- name: git username
  shell: git config user.name "{{ git_username }}"
  args:
    chdir: "{{ base_working_dir }}/{{ git_repo_path }}"
  when: git_username is defined

- name: git email
  shell: git config user.email "{{ git_email }}"
  args:
    chdir: "{{ base_working_dir }}/{{ git_repo_path }}"
  when: git_email is defined

- name: git commit
  shell: git commit -a -m "'{{ git_msg }}'"
  args:
    chdir: "{{ base_working_dir }}/{{ git_repo_path }}"
  ignore_errors: true
  register: git_commit_status

- block:
    - name: git push "{{ git_url }}"
      shell: git push "{{ git_url_with_token }}"
      no_log: true
      args:
        chdir: "{{ base_working_dir }}/{{ git_repo_path }}"

    - name: git status
      shell: git status
      args:
        chdir: "{{ base_working_dir }}/{{ git_repo_path }}"
      register: git_add_status
  when:
    - git_commit_status.rc == 0
    - not git_commit_status.stdout is search("nothing to commit")
